### ISSUE TITLE
Trouble opening TRDI OS 150 kHz  VmDas data

### ISSUE THREAD

**Issue by St0mat0p0d** [lkilcher/dolfyn#116]
I try to open an .lta file and it gives this error. 

`File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\dolfyn\io\rdi.py:1282, in _RDIReader.read_nocode(self, id)
   1277 logging.warning("Skipping bytes from codes 0340-30FC")
   1278 # I want to count the number of 1s in the middle 4 bits
   1279 # of the 2nd two bytes.
   1280 # 60 is a 0b00111100 mask
   1281 nflds = (bin(int(hxid[3]) & 60).count('1') +
-> 1282          bin(int(hxid[4]) & 60).count('1'))
   1283 # I want to count the number of 1s in the highest
   1284 # 2 bits of byte 3
   1285 # 3 is a 0b00000011 mask:
   1286 dfac = bin(int(hxid[3], 0) & 3).count('1')

ValueError: invalid literal for int() with base 10: 'e'`

**Comment by jmcvey3** [comment]
Hi @St0mat0p0d, I'm not particularly familiar with what data is stored in the .LTA file extension. Usually VMDAS outputs a .ENR, .ENS, and/or .ENX file that holds the profiling data (data in raw, instrument, and earth coordinates, respectively) which dolfyn can read.
