### ISSUE TITLE
loading hdf5 file

### ISSUE THREAD

**Issue by mthiebau** [lkilcher/dolfyn#22]
I'm using Python 2.7 and I have trouble loading a hdf5 file. I get the following error: 

 File "C:\MT\CODES\PYTHON\dolfyn\dolfyn\io\hdf5.py", line 624, in iter_groups if grp.__class__ is h5.highlevel.Group:

AttributeError: 'module' object has no attribute 'highlevel'

I tried with different versions of Dolfyn but the problem still remains.

**Comment by lkilcher** [comment]
Resolved by d65c5a4 (and 15df4a2a1aa0025002e53dab86b370f73ab02958 in v0.8).
