### ISSUE TITLE
issues with api.py

### ISSUE THREAD

**Issue by mthiebau** [lkilcher/dolfyn#47]
I encountered several issues when using this command: **import dolfyn.adp.api as apm**

Here are the warning messages I got:

1.  File "C:/ProgramData/Anaconda3/Lib/site-packages/test/adp_tests.py", line 1, in <module>
    import dolfyn.adp.api as apm
ImportError: cannot import name 'binner' from 'dolfyn.adp.base' (C:\ProgramData\Anaconda3\lib\site-packages\dolfyn\adp\base.py)

2. File "C:\ProgramData\Anaconda3\lib\site-packages\dolfyn\adp\api.py", line 3, in <module>
    from .api import read, load
ImportError: cannot import name 'read' from 'dolfyn.adp.api' (C:\ProgramData\Anaconda3\lib\site-packages\dolfyn\adp\api.py)

3. File "C:\ProgramData\Anaconda3\lib\site-packages\dolfyn\adp\api.py", line 3, in <module>from .api import read_rdi, load
 ImportError: cannot import name 'read_rdi' from 'dolfyn.adp.api' (C:\ProgramData\Anaconda3\lib\site-packages\dolfyn\adp\api.py)

I had those issues because I used a depreated interface of dolfyn. 
With the new interface (0.10.1) **import dolfyn.adp.api as apm** has to be change to **import dolfyn as dlfn**. 

Now all work just fine.

**Comment by lkilcher** [comment]
Thanks @mthiebau!

Yes, the dolfyn interface has changed. I'll work on fixing this for backwards compatability, but using the new interface is definitely the preferred approach.
