### ISSUE TITLE
read ADCP data from a specific ensemble to another

### ISSUE THREAD

**Issue by mthiebau** [lkilcher/dolfyn#48]
My concern is not actually a dolfyn issue.

I'm wandering if there is any way to just read ADCP data with **dlfn.read** from a specific ensemble to another. Is that possible? I just need some specific periods that I previously identified with WinADCP. Reading the entire raw data file takes time and it is not useful for what I want to do.

Thanks

**Comment by lkilcher** [comment]
Hi @mthiebau yes, this is possible. Use the `nens` input argument to `dolfyn.read`.

Did you close this because you figured this out for yourself, or?
