### ISSUE TITLE
>3 beam instruments

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn#53]
Data from instruments with more than 3 beams are not handled consistently. Different manufacturers use different beam-to-inst rotation matrices (e.g., RDI calculates *error velocity*, while Nortek just calculates another *vertical velocity*). More work is needed to figure out how to handle the extra information consistently.

**Comment by jmcvey3** [comment]
Currently this is handled by setting the `dir` coordinate to the TRDI vs Nortek convention.
