### ISSUE TITLE
bt_vel not in dat.props[rotate_vars] for RDI with bottom tracking

### ISSUE THREAD

**Issue by mcfogarty** [lkilcher/dolfyn#54]
dat = dolfyn.read(fname_rdi + '.000', keep_orient_raw=True)

yields 
dat.props['rotate_vars']  = {'vel'}

despite rdi.py having 
def load_data(self, nens=None):
.
.
.
        if 'bt_vel' in dat:
            dat['props']['rotate_vars'].update({'bt_vel', })

And dat object does have bt_vel after being read in.

**Comment by lkilcher** [comment]
Resolved by #50.
