### ISSUE TITLE
Deprecate `do_avg`, `do_var` and `do_tke`?

### ISSUE THREAD

**Issue by lkilcher** [lkilcher/dolfyn#69]
Not sure these functions are that valuable, and they add bulk to the codebase. I suggest we drop them. I still think the `__call__` method (which just averages everything) is useful, which calls `do_avg`, so we'll need to move that functionality somewhere. Maybe for now we just move it to `_do_avg`?

@jmcvey3, do you like them? If you don't have a strong opinion, I think we should drop those before merging #67.

**Comment by jmcvey3** [comment]
`do_avg` is a core function for ensembling the dataset, so how would you propose doing that if deprecated?
I agree that `do_tke` adds bulk.

**Comment by lkilcher** [comment]
Roger. Since `do_avg` is a major piece of the API, let's just leave `do_tke` in for now.

**Comment by lkilcher** [comment]
Also, I've changed my mind on the `__call__` method. Let's leave it out in favor of the more explicit `do_avg`.
