### ISSUE TITLE
Switch to logging module?

### ISSUE THREAD

**Issue by jklymak** [lkilcher/dolfyn#93]
The codebase has a lot of checks of `self._debug_level`.  Maybe easier to use the logging module: https://docs.python.org/3/library/logging.html ?

**Comment by lkilcher** [comment]
I like this idea. I’m adding this to the v1.1 milestone. @jmcvey3 is this something you can tackle?

**Comment by jmcvey3** [comment]
Good thing to add once the vmdas fix is completed, I think, and cover it all in one go.

**Comment by jmcvey3** [comment]
Implemented in v1.2
